# fly.toml app configuration file generated for oss-server on 2023-12-26T22:46:45+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "oss-server"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
